#pragma once

#include "SPHTraits.h"

namespace TNL {
namespace SPH {

/*
   Ghost band of one directed interface appended at the tail of the own boundary
   set. The geometry is static, fixed at init from an own-resolution wall lattice
   pre-generated by the init script (boundary-ghost-buffer-<p> file); interfaces
   without a ghost file have no ghost particles. Every step in interact(), ghost
   rho and gamma are refreshed by one of two methods selected by the
   boundary-ghost-method config entry: "interpolation" applies the MFD correction
   over the source boundary values, "direct-from-source" repeats the standard
   boundary-fluid update with the source fluid as the neighbor set.
   ghostIndices tracks the current slot of each ghost particle - ghosts are
   referential indices [ghostBegin, ghostBegin + numberOfGhostParticles) and their
   slots change when the boundary set is re-sorted by the neighbor search, so the
   array is re-derived from referentialIdx on every refresh call.
   See Documentation/multiresolution-ghost-boundaries-design.md.
*/
template< typename SPHConfig >
class BoundaryGhostParticles
{
public:
   using SPHTraitsType = SPHFluidTraits< SPHConfig >;
   using GlobalIndexType = typename SPHTraitsType::GlobalIndexType;
   using IndexArrayType = typename SPHTraitsType::IndexArrayType;

   int ownIdx = -1;
   int neighborIdx = -1;
   GlobalIndexType ghostBegin = 0;
   GlobalIndexType numberOfGhostParticles = 0;
   IndexArrayType ghostIndices;
};

enum class BoundaryGhostUpdate
{
   Interpolation,
   DirectFromSource
};

}  // namespace SPH
}  // namespace TNL
