CONFIGURATIONS = {

    # ── 2D configurations ─────────────────────────────────────────────────────

    "dummy2D-center": {
        "dimension": 2,
        "description": "Centered refinement in unit square",
        "dp": 0.002,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": 0.25,
        "fine_x_max": 0.75,
        "fine_y_min": 0.25,
        "fine_y_max": 0.75,
    },

    "dambreak2D-corner": {
        "dimension": 2,
        "description": "Dam break with refinement in bottom-right corner",
        "dp": 0.002,
        "h_coef": 1.75,
        "box_x": 1.61,
        "box_y": 0.6,
        "fine_factor": 0.5,
        "fine_x_min": 1.2,
        "fine_x_max": None,
        "fine_y_min": None,
        "fine_y_max": 0.3,
    },

    "dummy2D-pp-corner": {
        "dimension": 2,
        "description": "Refinement in ++ corner of unit square",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": 0.63,
        "fine_x_max": None,
        "fine_y_min": 0.85,
        "fine_y_max": None,
    },

    "dummy2D-pp-corner-h2": {
        "dimension": 2,
        "description": "Refinement in ++ corner of unit square, h=2",
        "dp": 0.02,
        "h_coef": 2,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": 0.65,
        "fine_x_max": None,
        "fine_y_min": 0.85,
        "fine_y_max": None,
    },

    "dummy2D-pm-corner": {
        "dimension": 2,
        "description": "Refinement in +- corner of unit square",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": 0.75,
        "fine_x_max": None,
        "fine_y_min": None,
        "fine_y_max": 0.75,
    },

    "dummy2D-mm-corner": {
        "dimension": 2,
        "description": "Refinement in -- corner of unit square",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": None,
        "fine_x_max": 0.34,
        "fine_y_min": None,
        "fine_y_max": 0.27,
    },

    "dummy2D-mp-corner": {
        "dimension": 2,
        "description": "Refinement in -+ corner of unit square",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": None,
        "fine_x_max": 0.25,
        "fine_y_min": 0.75,
        "fine_y_max": None,
    },

    "dummy2D-mp-corner-h2": {
        "dimension": 2,
        "description": "Refinement in -+ corner of unit square, h=2",
        "dp": 0.02,
        "h_coef": 2,
        "box_x": 1.0,
        "box_y": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": None,
        "fine_x_max": 0.25,
        "fine_y_min": 0.75,
        "fine_y_max": None,
    },

    # ── 3D configurations ─────────────────────────────────────────────────────

    "dummy3D-center": {
        "dimension": 3,
        "description": "Centered refinement in unit cube",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.0,
        "box_y": 1.0,
        "box_z": 1.0,
        "fine_factor": 0.5,
        "fine_x_min": 0.25,
        "fine_x_max": 0.75,
        "fine_y_min": 0.25,
        "fine_y_max": 0.75,
        "fine_z_min": 0.25,
        "fine_z_max": 0.75,
    },

    "dambreak3D-corner": {
        "dimension": 3,
        "description": "Dam break with refinement in bottom-right-front corner",
        "dp": 0.02,
        "h_coef": 1.75,
        "box_x": 1.61,
        "box_y": 0.6,
        "box_z": 0.6,
        "fine_factor": 0.5,
        "fine_x_min": 1.2,
        "fine_x_max": None,
        "fine_y_min": None,
        "fine_y_max": 0.3,
        "fine_z_min": None,
        "fine_z_max": 0.3,
    },

}
