# Simulation name, path to store results and path to read initial conditions
case-name = dummyMultiresolutionSimulation2D
output-directory = results
final-time = 0
snapshot-period = 0

# Particle system configuration
numberOfParticles = placeholderFluidParticles
numberOfAllocatedParticles = placeholderAllocatedFluidParticles
numberOfBoundaryParticles = placeholderBoundaryParticles
numberOfAllocatedBoundaryParticles = placeholderAllocatedBoundaryParticles

# Domain size and domain origin
searchRadius = placeholderSearchRadius
domainOrigin-x = placeholderDomainOrigin-x
domainOrigin-y = placeholderDomainOrigin-y
domainSize-x = placeholderDomainSize-x
domainSize-y = placeholderDomainSize-y

# Resolution parameters
dp = placeholderInitParticleDistance
h = placeholderSmoothingLength

# Domain decomposition information
numberOfSubdomains = 2
subdomains-config = placeholderSubdomainsConfigPath
